# Four tank system example - Fault Signature Matrix, row resoning

In [1]:
import pandas as pd
from isolability import pairwise_relationships as pr
from isolability import martices_and_indices as ind
from four_tanks.es import ess

#### Fault Signature Matrix

In [2]:
fsm_df = pd.read_csv('four_tanks/fsm.csv', sep=';', index_col=0)
fsm_df

f_1   f_2   f_3   f_4   f_5   f_6   f_7   f_8   f_9   f_10
s_1    1     1     1     1     1     1     1     1     1      0
s_2    1     1     1     1     1     1     1     1     0      1
s_3    0     1     1     1     1     1     1     0     1      1

In [3]:
fsm = fsm_df.to_numpy()
fsm

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 0, 1],
       [0, 1, 1, 1, 1, 1, 1, 0, 1, 1]])

#### Exploration of pairwise isolabity relationships
* Function arguments are fault **indices** starting from 0, so pr.RN_R_FSM(fsm, 1, 2) checks faults $f_2$ and $f_3$
* Avaliable relations:
    - RN_R_FSM - mutually non-isolable
    - RUN_R_FSM - unilaterally non-isolable
    - RUW_R_FSM - unilaterally (weakly) isolable
    - RW_R_FSM - bilaterally (weakly) isolable
    - RUS_R_FSM - unilaterally strongly isolable
    - RS_R_FSM - bilaterally strongly isolable

In [4]:
pr.RS_R_FSM(fsm, 7, 8)

np.False_

#### EIM matrix

In [6]:
eim = ind.EIM_R_FSM(fsm)
eim

array([[0., 0., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1., 1., 0.]])

#### $C\Delta$ coefficient

In [7]:
c_delta = ind.C_Delta(eim)
print(f"{c_delta:.3f}")

0.378


#### $C^*\Delta$ coefficient

In [8]:
c_star_delta = ind.C_star_Delta(eim)
print(f"{c_star_delta:.3f}")

0.378


#### IMES matrix

In [9]:
imes = ind.IMES(ess)
imes

array([[0., 0., 1., 1., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 1., 0., 0., 1., 0., 0., 0.],
       [1., 1., 0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### Weights for composition of EIM and IMES

In [14]:
comp_weights = pd.read_csv('conf/IMES_weights_FSM_R.csv', sep=';', index_col=0)
comp_weights

RW_ES   RJW_ES   RN_ES
RS_Rn_FSM       2      2.0     2.0
RUS_Rn_FSM      2      2.0     1.5
RW_R_FSM        2      1.5     1.0
RUW_R_FSM       2      1.4     1.0
RUN_R_FSM       1      0.7     0.0
RN_R_FSM        1      0.5     0.0

#### EIM$^*$

In [11]:
eim_star = ind.EIM_star_R_FSM(fsm, ess,comp_weights)
eim_star

array([[0., 0., 1., 1., 0., 0., 1., 0., 1., 1.],
       [1., 0., 1., 1., 0., 0., 1., 1., 1., 1.],
       [2., 1., 0., 0., 1., 0., 0., 1., 1., 1.],
       [2., 1., 0., 0., 1., 0., 0., 1., 1., 1.],
       [1., 0., 1., 1., 0., 0., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1., 1., 1.],
       [2., 1., 0., 0., 1., 0., 0., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1., 1., 0.]])

#### $C \Delta (EIM^*)$

In [12]:
c_delta = ind.C_Delta(eim_star)
print(f"{c_delta:.3f}")

0.578


#### $C^* \Delta (EIM^*)$

In [ ]:
c_star_delta = ind.C_star_Delta(eim_star)
print(f"{c_star_delta:.3f}")