# Four tank system example - Fault Signature Matrix, column resoning

In [2]:
import pandas as pd
from isolability import pairwise_relationships as pr
from isolability import martices_and_indices as ind
from four_tanks.es import ess

#### Fault Signature Matrix

In [3]:
fsm_df = pd.read_csv('four_tanks/fsm.csv', sep=';', index_col=0)
fsm_df

f_1   f_2   f_3   f_4   f_5   f_6   f_7   f_8   f_9   f_10
s_1    1     1     1     1     1     1     1     1     1      0
s_2    1     1     1     1     1     1     1     1     0      1
s_3    0     1     1     1     1     1     1     0     1      1

In [4]:
fsm = fsm_df.to_numpy()
fsm

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 0, 1],
       [0, 1, 1, 1, 1, 1, 1, 0, 1, 1]])

#### Exploration of pairwise isolabity relationships
* Function arguments are fault **indices** starting from 0, so pr.RN_C_FSM(fsm, 1, 2) checks faults $f_2$ and $f_3$
* Avaliable relations:
    - RN_C_FSM - non-isolable
    - RW_C_FSM - weakly isolable
    - RS_C_FSM - strongly isolable

In [5]:
pr.RN_C_FSM(fsm, 1, 2)

True

#### EIM matrix

In [7]:
eim = ind.EIM_C_FSM(fsm)
eim

array([[0., 1., 1., 1., 1., 1., 1., 0., 2., 2.],
       [1., 0., 0., 0., 0., 0., 0., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 0., 2., 2.],
       [2., 1., 1., 1., 1., 1., 1., 2., 0., 2.],
       [2., 1., 1., 1., 1., 1., 1., 2., 2., 0.]])

#### $C\Delta$ coefficient

In [ ]:
c_delta = ind.C_Delta(eim)
print(f"{c_delta:.3f}")

#### $C^*\Delta$ coefficient

In [ ]:
c_star_delta = ind.C_star_Delta(eim)
print(f"{c_star_delta:.3f}")

### Elementary Sequences

#### Exploration of pairwise relationships of isolability base on Elementary Sequences ES
* fault indices again start from 0
* Avaliable relations:
    - R_ES_N - non-isolable
    - R_ES_UW - unilaterally isolable
    - R_ES_W - isolable

In [9]:
pr.R_ES_W(ess, 0, 1)

False

#### IMES matrix

In [11]:
imes = ind.IMES(ess)
imes

array([[0., 0., 1., 1., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 1., 0., 0., 1., 0., 0., 0.],
       [1., 1., 0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### Weights for composition of EIM and IMES

In [18]:
comp_weights = pd.read_csv('conf/IMES_weights_FSM_C.csv', sep=';', index_col=0)
comp_weights

RW_ES   RJW_ES   RN_ES
RS_Cn_FSM      2      2.0       2
RW_C_FSM       2      1.5       1
RN_C_FSM       1      0.5       0

#### EIM$^*$

In [14]:
eim_star = ind.EIM_star_C_FSM(fsm, ess, comp_weights)
eim_star

array([[0., 1., 2., 2., 1., 1., 2., 0., 2., 2.],
       [1., 0., 1., 1., 0., 0., 1., 1., 1., 1.],
       [2., 1., 0., 0., 1., 0., 0., 1., 1., 1.],
       [2., 1., 0., 0., 1., 0., 0., 1., 1., 1.],
       [1., 0., 1., 1., 0., 0., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1., 1., 1.],
       [2., 1., 0., 0., 1., 0., 0., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 0., 2., 2.],
       [2., 1., 1., 1., 1., 1., 1., 2., 0., 2.],
       [2., 1., 1., 1., 1., 1., 1., 2., 2., 0.]])

#### $C \Delta (EIM^*)$

In [15]:
c_delta = ind.C_Delta(eim_star)
print(f"{c_delta:.3f}")

0.956


#### $C^* \Delta (EIM^*)$

In [16]:
c_star_delta = ind.C_star_Delta(eim_star)
print(f"{c_star_delta:.3f}")

0.778
